stages:
  - run

build:
  stage: run
  image: debian:12
  script:
    - apt-get update
    - apt-get install -y nodejs npm vim debhelper
    - npm install -g grunt-cli grunt-exec bower
    - cd src/
    - npm install
    - grunt dpkg-buildpackage --include-dependencies
    - ls dist/
  artifacts:
    paths:
      - src/dist/dimail-ui_*_all.deb

